spring:
  application:
    name: projeto-eco
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    open-in-view: false

  datasource:
    url: jdbc:mysql://localhost:3306/eco?useTimezone=true&serverTimezone=UTC
    username: root
    password: 7422
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs